### ISSUE TITLE
New CMake version

### ISSUE THREAD

**Issue by GHlacour** [GHlacour/NISE_2017#16]
**Describe the bug**
The code does not compile with CMake/3.18.4-GCCcore-10.2.0

**To Reproduce**
1. CMake with module load CMake/3.18.4-GCCcore-10.2.0
2. When running make a complaint on:
/software/software/binutils/2.31.1-GCCcore-8.2.0/bin/ld.gold: error: CMakeFiles/NISE.dir/types_MPI.c.o: multiple definition of 'T_NON_TYPE'
/software/software/binutils/2.31.1-GCCcore-8.2.0/bin/ld.gold: CMakeFiles/NISE.dir/NISE.c.o: previous definition here

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
